language: minimal

script:
  - mkdir build
  - cd build
  - cmake .. && make -j $(nproc --all || sysctl -n hw.ncpu)

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gcc@8 --force; fi
  - export CC
  - export CXX

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gcc-4.8
            - g++-4.8
            - mpi-default-dev
      env: CC=gcc-4.8 CXX=g++-4.8
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-8
            - mpi-default-dev
      env: CC=gcc-8 CXX=g++-8
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - mpi-default-dev
      env: CC=clang-3.6 CXX=clang++-3.6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - mpi-default-dev
      env: CC=clang-7 CXX=clang++-7
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gcc-4.8
            - g++-4.8
      env: CC=gcc-4.8 CXX=g++-4.8
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-8
      env: CC=gcc-8 CXX=g++-8
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env: CC=clang-3.6 CXX=clang++-3.6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
      env: CC=clang-7 CXX=clang++-7
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - cmake
            - gcc@8
      env: CC=gcc-8 CXX=g++-8
