language: cpp

compiler:
  - clang
  - gcc

os:
- linux
- osx

before_install:
- git submodule update --init --recursive
- test -n $CC  && unset CC
- test -n $CXX && unset CXX

script:
- mkdir build
- cd build
- cmake .. && make

