language: minimal

script:
- mkdir build
- cd build
- cmake .. && make
-
before_install:
  - export CC
  - export CXX

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gcc-4.8
            - g++-4.8
            - mpi-default-dev
      env: CC=gcc-4.8 CXX=g++-4.8
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6
            - mpi-default-dev
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
            - mpi-default-dev
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - mpi-default-dev
      env: CC=clang-3.6 CXX=clang++-3.6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - cmake
            - clang-4.0
            - mpi-default-dev
      env: CC=clang-4.0 CXX=clang++-4.0
